require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '10.0'

target 'brainbytescreativeactearly' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'brainbytescreativeactearlyTests' do
    inherit! :complete
    # Pods for testing
  end

  use_native_modules!
    use_unimodules!(exclude: ['expo-face-detector', 'expo-file-system', 'expo-permissions','expo-image-picker', 'expo-in-app-purchases', 'expo-web-browser', 'expo-updates', 'expo-constants', 'expo-image-loader', 'unimodules-barcode-scanner-interface', 'unimodules-camera-interface', 'unimodules-constants-interface', ' unimodules-face-detector-interface', 'unimodules-image-loader-interface', 'unimodules-sensors-interface', 'unimodules-task-manager-interface'])

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper' => '0.95.0' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'brainbytescreativeactearly-tvOS' do
  # Pods for brainbytescreativeactearly-tvOS

  target 'brainbytescreativeactearly-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
